#!/bin/sh

tmp=${TMPDIR-/tmp}/pacman-disowned-$UID-$$
db=$tmp/db
fs=$tmp/fs

mkdir "$tmp"
trap 'rm -rf "$tmp"' EXIT

/usr/sbin/pacman -Qlq | sort -u > "$db"

sudo ionice -c 3 nice -17 find /bin /etc /lib /sbin /usr \
         ! -name lost+found \
         \( -type d -printf '%p/\n' -o -print \) | sort > "$fs"

comm -23 "$fs" "$db"
